<?php echo $this->doctype(); ?>
<html lang="de-de">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <?php echo $this->headTitle('Newsfeed') ?>

        <?= $this->partial('_includes.phtml'); ?>
    </head>

    <body class="text-center">
        <?php echo $this->content; ?>

    </body>
</html>
