
<h1>Mit Alexa verknüpfen</h1>

<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Amazon Alexa Login
            </div>
            <div class="panel-body">
                <form role="form" action="/Dashboard/linkWithAmazon?save=true" method="post">
                    <div class="form-group">
                        <label>E-Mail-Adresse</label>
                        <input class="form-control" type="text" name="AmazonUsername" value="<?= $this->objUser->AmazonUsername;?>">
                    </div>
                    <div class="form-group">
                        <label>Passwort</label>
                        <input class="form-control" type="password" name="AmazonPassword" value="<?= str_repeat('*', strlen($this->objUser->AmazonPassword));?>">
                    </div>


                    <button type="submit" class="btn btn-default">Speichern</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Basic Form Elements
            </div>
            <div class="panel-body">
                <div id="alexas">Einen Moment Geduld bitte...</div>
                <script>
                    $.ajax({
                        url: '/Dashboard/checkAmazonLinking',
                        dataType: 'text',
                        success: function (data)
                        {
                            $('#alexas').html(data);
                        }
                    });
                    function updateSelectedAlexas(strAlexaId, boolActivated)
                    {
                        $.ajax({
                            url: '/Dashboard/enableDisableAlexa?strAlexaId=' + strAlexaId,
                            dataType: 'text',
                            success: function (data){}
                        });
                    }
                </script>
            </div>
        </div>
    </div>
</div>